name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # sudo add-apt-repository ppa:gnome3-team/gnome3  # 添加更新源
          sudo apt-get update
          sudo apt-get install -y ninja-build python3-pip valac libadwaita-1-dev pkg-config libadwaita-1-0
          pip3 install --upgrade meson

      - name: Configure project
        run: meson . _build --prefix=$(pwd)/_install_dir  # 使用相对路径

      - name: Build project
        run: ninja -C _build all

      - name: Install to local directory
        run: ninja -C _build install

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: _install_dir  # 指定生成文件的目录
