name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Check wget version
        run: wget --version
        
      - name: Install dependencies
        run: |
          cat /etc/apt/sources.list
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y \
            libgirepository1.0-dev \
            libgtk-4-dev \
            gir1.2-adw-1 \
            libadwaita-1-0 \
            libappstream-dev \
            gir1.2-gio-2.0-dev \
            gir1.2-gtk-4.0-dev \
            ninja-build \
            python3-pip \
            valac \
            pkg-config

          # Install specific version of libadwaita if needed
          # wget http://archive.ubuntu.com/ubuntu/pool/main/liba/libadwaita-1/libadwaita-1-dev_1.5.0-1ubuntu2_amd64.deb
          # sudo dpkg -i libadwaita-1-dev_1.5.0-1ubuntu2_amd64.deb || echo "No such file, proceeding with other dependencies."
          sudo apt-get install -f -y

          # Upgrade meson
          pip3 install --upgrade meson

          # Install TypeScript (if necessary)
          sudo apt-get install -y typescript

          # Install GObject Introspection and Blueprint Compiler
          sudo apt-get install -y gobject-introspection
          sudo apt-get install -y blueprint-compiler

      - name: Configure project
        run: meson . _build --prefix=$(pwd)/_install_dir

      - name: Build project
        run: ninja -C _build all

      - name: Install to local directory
        run: ninja -C _build install

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: _install_dir
